### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by Khallie** [FatigueDev/typing_indicator#2]
Last couple of days had issues with seeing the word Typing just hanging in the air with no one there. Today client crashed a couple of times when I was trying to type in the chat window.
[Wsu6MKgR.txt](https://github.com/user-attachments/files/16115485/Wsu6MKgR.txt)

**Comment by FatigueDev** [comment]
Can you verify their game language and the configuration of the server? Defaults are English, with the option for other langs but it's sort of iffy. If you can mail me your config and let me know their localization I'll see what I can do

**Comment by Khallie** [comment]
Hi, the default is English, I am playing on a public server so I cannot send you the config. I can ask the owner if he can.

**Comment by WickedSchnitzel** [comment]
That's our config. Should be "Thinking...", not "Typing..."

[config.json](https://github.com/user-attachments/files/16118261/config.json)

There was an folder named out_of_date_configs
 as well which included another json. i have deleted that one just now, it may interfere with the other json.

**Comment by FatigueDev** [comment]
The `out_of_date_configs` folder is when Typing Indicator has an update and it might cause conflicts since packets may change, or new localizations may be added. I think what's happening is the player isn't being given the config- So their DisplayText is null at the point of trying to use it. I'll write a quick patch for this null check and test it.

**Comment by FatigueDev** [comment]
Should be fixed with https://github.com/FatigueDev/typing_indicator/commit/c2f85ade24eb610f918c353f070bed98787293ea. I'll push the new version to the ModDB. @WickedSchnitzel , remember to update your ModConfig/TypingIndicator since it will be replaced.

**Comment by WickedSchnitzel** [comment]
I have updated it to the latest version but it does not create a config file

**Comment by FatigueDev** [comment]
> I have updated it to the latest version but it does not create a config file

So the contents of ModConfig/typing_indicator/ is empty after running the new version? What's happening when you go into thirdperson and try to type?

**Comment by WickedSchnitzel** [comment]
It says "Typing...". Maybe it uses the json on my harddrive, since i have deleted the typing_indicator folder on the server to let in generate from scratch, but it did not.

**Comment by FatigueDev** [comment]
So it defaults to the contents of https://github.com/FatigueDev/typing_indicator/blob/c2f85ade24eb610f918c353f070bed98787293ea/TypingIndicator/TypingIndicatorDefaultConfigurations.cs#L8

This is a dumb question, but you restarted the server since removing it, right? In the meantime, I'll provide you with a replacement config. [config.json](https://github.com/user-attachments/files/16118572/config.json)

Simply add that to ModConfig/typing_indicator/config.json while I try and get to the bottom of it.
